"""Modern brand theme — clean, soft depth, pro UI feel."""

from dsa_anim.themes.base import ThemeSpec

MODERN = ThemeSpec(
    name="modern",
    background_color="#F7F7FB",
    font_family="sans-serif",
    font_size_heading=56,
    font_size_section_heading=42,
    font_size_body=28,
    font_size_caption=20,
    font_size_code=22,
    primary="#111827",
    accent="#4F46E5",
    success="#10B981",
    warning="#F59E0B",
    error="#EF4444",
    muted="#9CA3AF",
    text_color="#111827",
    text_light="#6B7280",
    box_fill="#FFFFFF",
    box_border="#E5E7EB",
    box_border_width=1.6,
    box_corner_radius=12.0,
    box_padding=18.0,
    box_min_width=150.0,
    box_min_height=58.0,
    token_fill="#F3F4F6",
    token_border="#CBD5E1",
    token_padding=10.0,
    token_corner_radius=10.0,
    connector_color="#94A3B8",
    connector_width=2.0,
    arrow_size=10.0,
    gap_small=14.0,
    gap_medium=26.0,
    gap_large=54.0,
    margin=64.0,
    sketch_effect=False,
    shadow=True,
    shadow_offset=6.0,
    shadow_blur=14.0,
    shadow_color="#0000001A",
)
