"""Material-inspired theme with calm surfaces and clear hierarchy."""

from kaivra.themes.base import ThemeSpec

MATERIAL = ThemeSpec(
    name="material",
    background_color="#F6F8FC",
    font_family="sans-serif",
    font_size_heading=54,
    font_size_section_heading=40,
    font_size_body=27,
    font_size_caption=19,
    font_size_code=21,
    primary="#1F2937",
    accent="#1976D2",
    success="#2E7D32",
    warning="#ED6C02",
    error="#D32F2F",
    muted="#B0BEC5",
    text_color="#1F2937",
    text_light="#5F6B7A",
    box_fill="#FFFFFF",
    box_border="#D7E3F1",
    box_border_width=1.5,
    box_corner_radius=16.0,
    box_padding=20.0,
    box_min_width=156.0,
    box_min_height=60.0,
    token_fill="#EAF2FD",
    token_border="#90CAF9",
    token_padding=10.0,
    token_corner_radius=12.0,
    connector_color="#90A4AE",
    connector_width=2.0,
    arrow_size=11.0,
    gap_small=16.0,
    gap_medium=28.0,
    gap_large=56.0,
    margin=64.0,
    sketch_effect=False,
    shadow=True,
    shadow_offset=8.0,
    shadow_blur=20.0,
    shadow_color="#001D351A",
)
